### ISSUE TITLE
Maps not working

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#10]
The property map no longer shows. This seems to have happened since google now required an API key to use maps. How can I fix this?
Thanks 

-Originally asked by chrisoliver1990 on 12-07-2016, 08:27 PM, migrated from site forum

**Comment by Markup360** [comment]
Hi Chris,

Do you have a link to your site?

**Comment by livingwandsworth** [comment]
Hi Naz,

The map on my site is also not working. But it is working before when I am using my previous theme(Placester).

**Comment by Markup360** [comment]
I hope to have a fix for this by the end of the week, this is due to a change by Google.

**Comment by livingwandsworth** [comment]
Hi Naz,

Thanks in advance. We will wait for the fix.

**Comment by Markup360** [comment]
Hi Naz,

Do we have an update regarding the fix? Thanks.

**Comment by Markup360** [comment]
Hi Herbin,

Not yet, I did think it would be easy, but it turns out one of the issues is in a plugin that we use and we need to wait for that to be updated first.

**Comment by livingwandsworth** [comment]
Hi Naz,

Do we have an update regarding the fix? Thanks.

**Comment by Markup360** [comment]
Hi Herbin,

Not yet, I did think it would be easy, but it turns out one of the issues is in a plugin that we use and we need to wait for that to be updated first.

**Comment by Markup360** [comment]
The plugin has been updated, so now I need to make some final changes and hopefully there will be a new RealEstatePro either later today or tomorrow. You will however, need to obtain a Google Maps API key.

**Comment by livingwandsworth** [comment]
Hi Naz,

Yes I already an API key. Hopefully this issue will be fixed now. Thanks.

**Comment by livingwandsworth** [comment]
KBW says;

Hi Naz

Re: Graviton
Still a neebie so cant be sure why the google map isn't showing. I have added an API key. Although can't be sure done that properly either. So by adding the API key - should that be sufficient to get the map to show? Will it also need a short time to actually permeate through and will only show on the live site (ie not in preview)

Thanks

Keith

**Comment by Markup360** [comment]
New release coming out imminently that will resolve this, make sure you are signed up to the newsletter.

**Comment by Markup360** [comment]
This has now been fixed in the latest version. To update to the latest version;

1. Backup your site, and I recommend testing first before using on a live environment.
2. Download the latest version of RealEstatePro, open the package and copy the RealEstatePro theme folder.
3. From your installation go to wp-content/themes and delete your RealEstatePro theme.
4. Paste/transfer the latest version.
5. To add your Google Maps API from the Admin go to Appearance>Customize>Google Maps Options and paste in your API key.

Visit our page https://www.markup360.com/content/10-usi...ps-api-key to find out how to obtain a Google Maps API key.

That should be all you need to do, if you run in to any issues let me know.

**Comment by livingwandsworth** [comment]
Hi Naz,

I have already updated RealEstatepro and pasted my API key. Unfortunately the map is still not working. When I am checking the properties page in the admin section to enter the location. The Map will show momentarily and then will disappear again and an error message will be displayed.

**Comment by Markup360** [comment]
It sounds like the API key has not been activated, go to your Google Maps API credentials page and ensure that the key is activated. Also ensure that under Overview>Enabled APIs all the APIs are enabled. If that doesn't work PM you website details and I will have a look.

**Comment by livingwandsworth** [comment]
Hi Naz,

Its all working now. Thank you very much. You are real savior.
